### ISSUE TITLE
메세지 조사 문제

### ISSUE THREAD

**Issue by zerohouse** [NHNNEXT/2015-03-REAL-TUTU#44]
새로운 게시물 'UDP 프로토콜 구현' 가 등록되었습니다.

--> 은는이가을를 조사 문제.

**Comment by hataeho1** [comment]
https://github.com/NHNNEXT/2015-03-REAL-TUTU/blob/master/src%2Fmain%2Fjava%2Forg%2Fnext%2Finfra%2Futil%2FHanGuelUtil.java
