### ISSUE TITLE
메일에서 비밀번호 변경 수행시 유효성 검증하는 로직 필요

### ISSUE THREAD

**Issue by hataeho1** [NHNNEXT/2015-03-REAL-TUTU#60]

**Comment by zerohouse** [comment]
이거 어차피 서버에서는 DB단에서 막으니까 클라에서만 체크하면 되는데

**Comment by zerohouse** [comment]
function validateEmail(email) {
    var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email);
}
